const {test,expect}=require('@playwright/test');
const U='10000000-0000-4000-8000-000000000001',V='10000000-0000-4000-8000-000000000002',A='20000000-0000-4000-8000-000000000001',B='20000000-0000-4000-8000-000000000002',D='AUDIT_MESSENGER_PHONE';
const MID='30000000-0000-4000-8000-000000000001';
test.setTimeout(7000);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function fixture(browser,{mobile=false,message='Initial text',mode='normal',manager=false,readOnly=false}={}){
 const context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1280,height:800}});
 const h={context,posted:[],groupAttempts:[],changed:{},reads:[],loads:{},deny:false,release:null,mode,committed:[],pageErrors:[],failed:[]};
 const rows=id=>[{id:MID,thread_id:id,sender_user_id:V,sender_display_name:'Synthetic Recipient',body:message,message_type:'text',sent_at:'2026-10-06T15:00:00Z',metadata_json:{}}].concat(h.committed.filter(x=>x.thread_id===id));
 await context.route('https://memphis-zoo-mcp.onrender.com/**',async route=>{
  const req=route.request(),url=new URL(req.url()),path=url.pathname;
  const json=(status,data,meta={})=>route.fulfill({status,contentType:'application/json',headers:{'Access-Control-Allow-Origin':req.headers().origin||'http://127.0.0.1:4388','Access-Control-Allow-Credentials':'true','Access-Control-Allow-Headers':'Content-Type, Authorization, X-Device-Id','Access-Control-Allow-Methods':'GET,POST,OPTIONS'},body:JSON.stringify(status<400?{ok:true,data,meta}:{ok:false,error:'Synthetic access denied',code:'access_revoked'})});
  if(req.method()==='OPTIONS')return json(200,{});
  if(path==='/auth-api/session')return json(200,{session:{token:'SYNTHETIC-MANAGER',role:'ops_manager',roles:['OPS_MANAGER','CUSTODIAL_MANAGER'],manager_id:U,device_id:D,credential_id:'SYNTHETIC-CREDENTIAL',access_level:readOnly?'read_only':'full_access',read_only:readOnly,expires_at:'2030-01-01T00:00:00Z',permissions:{schema:'custodial.manager-permissions.v1',owner:!readOnly,read:true}},trusted_device:{device_id:D}});
  if(path==='/messaging-api/me/by-device')return json(200,{msg_user_id:U,display_name:'Synthetic Employee',role:manager?'manager':'employee',read_only:readOnly,canonical_device_id:D});
  if(path==='/messaging-api/threads')return h.deny?json(403,{}):json(200,[A,B].map((id,i)=>({thread_id:id,thread_type:'direct',thread_title:i?'Conversation B':'Conversation A',viewer_can_send:!readOnly,participant_names:'Synthetic Employee, Synthetic Recipient',last_message_at:'2026-10-06T15:00:00Z',last_message_body:'Initial text'})));
  if(path==='/messaging-api/users')return json(200,[{id:V,display_name:'Synthetic Recipient',role:'employee',is_active:true},{id:'10000000-0000-4000-8000-000000000003',display_name:'Synthetic Other Recipient',role:'employee',is_active:true}]);
  const id=path.includes(A)?A:B;
  if(path.endsWith('/messages')){h.loads[id]=(h.loads[id]||0)+1;return h.deny?json(403,{}):json(200,rows(id));}
  if(path.endsWith('/message')&&req.method()==='POST'){
   const body=req.postDataJSON();h.posted.push({thread:id,...body});
   if(h.mode==='hold')await new Promise(r=>{h.release=r;});
   if(h.mode==='offline')return route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({ok:false,error:'Synthetic network outage'})});
   const row={id:'30000000-0000-4000-8000-'+String(h.posted.length+10).padStart(12,'0'),thread_id:id,sender_user_id:U,sender_display_name:'Synthetic Employee',body:body.body,message_type:'text',sent_at:new Date().toISOString(),metadata_json:{client_message_id:body.client_message_id}};
   if(!h.committed.some(x=>x.metadata_json.client_message_id===body.client_message_id))h.committed.push(row);
   return json(200,{id:row.id,status:'sent'});
  }
  if(path.endsWith('/read')){h.reads.push(req.postDataJSON());return json(readOnly?403:200,{marked:true});}
  if(path==='/messaging-api/thread/group'){h.groupAttempts.push(req.postDataJSON());return json(h.mode==='group-lost'&&h.groupAttempts.length===1?503:200,{id:A});}
  if(path.endsWith('/updates')){await sleep(120);const changed=h.changed[id];h.changed[id]=false;return h.deny?json(403,{}):json(200,changed?[{id:MID,thread_id:id}]:[],{next_cursor:{after:'2026-10-06T15:00:00Z',after_id:MID}});}
  if(path.endsWith('/thread/direct'))return json(200,{id:A});
  return json(200,{});
 });
 const page=await context.newPage();h.page=page;page.on('pageerror',e=>h.pageErrors.push(e.message));page.on('requestfailed',r=>h.failed.push(r.failure()?.errorText));
 await page.goto(`/messages.html?thread_id=${A}&device=${D}&hub=${manager?'manager':'employee'}`);
 await expect(page.locator('.cs-message-input__content-editor')).toBeVisible();
 await expect.poll(()=>h.loads[A]).toBeGreaterThan(0);await sleep(100);
 h.editor=page.locator('.cs-message-input__content-editor');
 h.switchTo=async id=>{if(mobile)await page.getByRole('button',{name:'Back to conversations'}).click();await page.locator('.cs-conversation').filter({hasText:id===A?'Conversation A':'Conversation B'}).click();await expect(page.locator('.cs-conversation-header__user-name')).toHaveText(id===A?'Conversation A':'Conversation B');};
 h.close=async()=>{h.release?.();await context.close();};return h;
}
test('AUD-01 message bodies are literal text rather than HTML',async({browser})=>{const text='<b data-audit-markup="yes">Literal markup</b> & text';const h=await fixture(browser,{message:text});try{await expect(h.page.locator('.cs-message__content [data-audit-markup]')).toHaveCount(0,{timeout:700});await expect(h.page.locator('.cs-message__content')).toHaveText(text);}finally{await h.close();}});
test('AUD-02 emoji sequences round-trip from composer to received bubble',async({browser})=>{const h=await fixture(browser);try{const text='Ready 👍🏽 👨‍👩‍👧‍👦 🇺🇸 ❤️ 🦁';await h.editor.fill(text);await h.editor.press('Enter');await expect.poll(()=>h.posted.length).toBe(1);expect(h.posted[0].body).toBe(text);await expect(h.page.locator('.cs-message--outgoing .cs-message__content')).toHaveText(text);expect(h.pageErrors).toEqual([]);}finally{await h.close();}});
test('AUD-03 valid Unicode message length agrees with backend code-point limit',async({browser})=>{const h=await fixture(browser);try{const text='👍'.repeat(1001);await h.editor.fill(text);await h.editor.press('Enter');await expect.poll(()=>h.posted.length,{timeout:700}).toBe(1);expect(h.posted[0].body).toBe(text);}finally{await h.close();}});
test('AUD-04 unsent draft stays with its original conversation',async({browser})=>{const h=await fixture(browser);try{await h.editor.fill('Draft only for A');await h.switchTo(B);await expect(h.editor).toHaveText('',{timeout:700});await h.switchTo(A);await expect(h.editor).toHaveText('Draft only for A');}finally{await h.close();}});
test('AUD-05 completing a send never navigates away from a newly opened conversation',async({browser})=>{const h=await fixture(browser,{mode:'hold'});try{await h.editor.fill('Sending to A');await h.editor.press('Enter');await expect.poll(()=>h.posted.length).toBe(1);await h.switchTo(B);h.mode='normal';h.release();await expect.poll(()=>h.committed.length).toBe(1);await sleep(200);await expect(h.page.locator('.cs-conversation-header__user-name')).toHaveText('Conversation B',{timeout:700});}finally{await h.close();}});
test('AUD-06 pending local message survives a normal thread refresh',async({browser})=>{const h=await fixture(browser,{mode:'hold'});try{await h.editor.fill('Pending durable message');await h.editor.press('Enter');await expect.poll(()=>h.posted.length).toBe(1);const before=h.loads[A];h.changed[A]=true;await expect.poll(()=>h.loads[A]).toBeGreaterThan(before);await expect(h.page.locator('.cs-message__content').filter({hasText:'Pending durable message'})).toBeVisible({timeout:700});}finally{await h.close();}});
test('AUD-07 access denial withdraws previously rendered private messages',async({browser})=>{const h=await fixture(browser,{message:'PRIVATE TEST BODY'});try{h.deny=true;await h.page.evaluate(()=>window.dispatchEvent(new Event('pageshow')));await expect(h.page.locator('.cs-message__content').filter({hasText:'PRIVATE TEST BODY'})).toHaveCount(0,{timeout:850});}finally{await h.close();}});
test('AUD-08 Send target is at least 44 by 44 CSS pixels on phone',async({browser})=>{const h=await fixture(browser,{mobile:true});try{await h.editor.fill('tap target');const box=await h.page.locator('.cs-button--send').boundingBox();expect(box.width).toBeGreaterThanOrEqual(44);expect(box.height).toBeGreaterThanOrEqual(44);}finally{await h.close();}});
test('AUD-09 durable offline message remains visible after reopening its thread',async({browser})=>{const h=await fixture(browser,{mode:'offline'});try{await h.editor.fill('Saved offline draft');await h.editor.press('Enter');await expect.poll(()=>h.posted.length).toBeGreaterThan(0);await h.switchTo(B);await h.switchTo(A);await expect(h.page.locator('.cs-message__content').filter({hasText:'Saved offline draft'})).toBeVisible({timeout:700});}finally{await h.close();}});
test('AUD-10 full local storage never clears an unsaved composer',async({browser})=>{const h=await fixture(browser);try{await h.page.evaluate(()=>{const original=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k.startsWith('mz_chatscope_outbox:'))throw new DOMException('Synthetic full storage','QuotaExceededError');return original.call(this,k,v);};});await h.editor.fill('Do not lose this text');await h.editor.press('Enter');await expect(h.editor).toHaveText('Do not lose this text',{timeout:700});expect(h.posted).toHaveLength(0);}finally{await h.close();}});

test('AUD-11 emoji picker inserts at the captured caret and sends exact Unicode',async({browser})=>{const h=await fixture(browser,{mobile:true});try{await h.editor.fill('Before after');await h.editor.evaluate(el=>{const r=document.createRange();r.setStart(el.firstChild,7);r.collapse(true);const s=window.getSelection();s.removeAllRanges();s.addRange(r);el.focus();});await h.page.getByRole('button',{name:'Insert emoji'}).click();await expect(h.page.getByRole('group',{name:'Emoji picker'})).toBeVisible();await h.page.getByRole('button',{name:'Thumbs up',exact:true}).click();await expect(h.editor).toHaveText('Before 👍after');await h.editor.press('Enter');await expect.poll(()=>h.posted.length).toBe(1);expect(h.posted[0].body).toBe('Before 👍after');await expect(h.page.locator('.cs-message--outgoing .cs-message__footer')).toHaveText('Sent to server');}finally{await h.close();}});
test('AUD-12 emoji picker closes with Escape and returns keyboard focus',async({browser})=>{const h=await fixture(browser);try{const button=h.page.getByRole('button',{name:'Insert emoji'});await button.click();await expect(h.page.getByRole('button',{name:'Thumbs up',exact:true})).toBeFocused();await h.page.keyboard.press('Escape');await expect(h.page.getByRole('group',{name:'Emoji picker'})).toHaveCount(0);await expect(button).toBeFocused();expect(h.posted).toHaveLength(0);}finally{await h.close();}});
test('AUD-13 line breaks and literal angle brackets are not stripped',async({browser})=>{const h=await fixture(browser);try{const text='First <room> & notes\nSecond line 👍';await h.editor.fill(text);await h.editor.press('Enter');await expect.poll(()=>h.posted.length).toBe(1);expect(h.posted[0].body).toBe(text);await expect(h.page.locator('.cs-message--outgoing .cs-message__content')).toHaveText(text);}finally{await h.close();}});
test('AUD-14 double Send clicks produce one message while a response is pending',async({browser})=>{const h=await fixture(browser,{mode:'hold'});try{await h.editor.fill('Only once');await h.page.locator('.cs-button--send').dblclick();await expect.poll(()=>h.posted.length).toBe(1);await sleep(200);expect(h.posted).toHaveLength(1);h.mode='normal';h.release();await expect.poll(()=>h.committed.length).toBe(1);await expect(h.page.locator('.cs-message--outgoing')).toHaveCount(1);}finally{await h.close();}});
test('AUD-15 emoji picker never carries into a different conversation',async({browser})=>{const h=await fixture(browser);try{await h.editor.fill('A text');await h.page.getByRole('button',{name:'Insert emoji'}).click();await h.switchTo(B);await expect(h.page.getByRole('group',{name:'Emoji picker'})).toHaveCount(0);await expect(h.editor).toHaveText('');await h.page.getByRole('button',{name:'Insert emoji'}).click();await h.page.getByRole('button',{name:'Broom',exact:true}).click();await expect(h.editor).toHaveText('🧹');await h.editor.press('Enter');await expect.poll(()=>h.posted.length).toBe(1);expect(h.posted[0].thread).toBe(B);}finally{await h.close();}});
test('AUD-16 no horizontal page overflow or clipped send button on narrow phones',async({browser})=>{const h=await fixture(browser,{mobile:true});try{await h.page.setViewportSize({width:320,height:640});await h.editor.fill('Narrow phone');const metrics=await h.page.evaluate(()=>({width:innerWidth,bodyWidth:document.body.scrollWidth,send:document.querySelector('.cs-button--send').getBoundingClientRect().toJSON(),focusOutline:getComputedStyle(document.querySelector('.cs-button--send')).outlineStyle}));expect(metrics.bodyWidth).toBeLessThanOrEqual(metrics.width);expect(metrics.send.right).toBeLessThanOrEqual(metrics.width);expect(metrics.send.bottom).toBeLessThanOrEqual(640);await h.page.screenshot({path:'../evidence/messenger-phone-320.png',fullPage:true});await h.page.setViewportSize({width:1280,height:800});await h.page.screenshot({path:'../evidence/messenger-desktop.png',fullPage:true});}finally{await h.close();}});

test('AUD-17 read-only managers may read without sending forbidden receipt mutations',async({browser})=>{const h=await fixture(browser,{manager:true,readOnly:true,message:'Read-only visible message'});try{await sleep(250);await expect(h.page.locator('.cs-message__content')).toHaveText('Read-only visible message');expect(h.reads).toHaveLength(0);await expect(h.page.getByRole('button',{name:'Insert emoji'})).toBeDisabled();await h.page.getByRole('button',{name:'Back to conversations'}).click();await expect(h.page.getByRole('button',{name:'New',exact:true})).toBeDisabled();}finally{await h.close();}});
test('AUD-18 uncertain group creation retries retain the same request identity',async({browser})=>{const h=await fixture(browser,{manager:true,mode:'group-lost'});try{await h.page.getByRole('button',{name:'Back to conversations'}).click();await h.page.getByRole('button',{name:'New',exact:true}).click();await h.page.locator('.mz-chat-user').filter({hasText:'Synthetic Recipient'}).locator('input').check();await h.page.locator('.mz-chat-user').filter({hasText:'Synthetic Other Recipient'}).locator('input').check();await h.page.getByRole('button',{name:'Create',exact:true}).click();await expect.poll(()=>h.groupAttempts.length).toBe(1);await expect(h.page.getByRole('button',{name:'Create',exact:true})).toBeEnabled();await h.page.getByRole('button',{name:'Create',exact:true}).click();await expect.poll(()=>h.groupAttempts.length).toBe(2);expect(h.groupAttempts[1].client_thread_id).toBe(h.groupAttempts[0].client_thread_id);}finally{await h.close();}});
test('AUD-19 composing Enter never sends unfinished IME text',async({browser})=>{const h=await fixture(browser);try{await h.editor.fill('Composing text');await h.editor.dispatchEvent('keypress',{key:'Enter',code:'Enter',charCode:13,keyCode:13,which:13,isComposing:true,bubbles:true});await sleep(150);expect(h.posted).toHaveLength(0);await expect(h.editor).toHaveText('Composing text');}finally{await h.close();}});
