(() => {
  'use strict';
  const android = /Android/i.test(navigator.userAgent || '');
  document.documentElement.classList.add('mz-native-app', android ? 'mz-native-android' : 'mz-native-ios');
  if (document.getElementById('mz-native-layout-contract')) return;
  const style = document.createElement('style');
  style.id = 'mz-native-layout-contract';
  style.textContent = `html.mz-native-app{--mz-native-bottom-guard:${android ? '78px' : 'max(10px,env(safe-area-inset-bottom))'};--mz-back-width:116px;--mz-back-height:52px}html.mz-native-app body{min-height:100vh;padding-bottom:var(--mz-native-bottom-guard)!important}html.mz-native-android body>main,html.mz-native-android body>.page,html.mz-native-android body>.shell{padding-bottom:108px!important}html.mz-native-app .build,html.mz-native-app .buildStamp{display:none!important}html.mz-native-app .mz-page-header{min-height:68px!important;display:flex!important;align-items:flex-start!important;justify-content:flex-start!important;padding:8px 0 0 8px!important}html.mz-native-app .mz-back-link{width:var(--mz-back-width)!important;min-width:var(--mz-back-width)!important;height:var(--mz-back-height)!important;min-height:var(--mz-back-height)!important;padding:0 14px!important;border-radius:16px!important;font-size:.94rem!important}@supports selector(tr:has(.status-not_cleaned)){html.mz-native-app tbody tr:has(.status-not_cleaned) td:nth-child(n+3){display:none!important}@media(max-width:640px){html.mz-native-app tbody tr:has(.status-not_cleaned){display:grid!important;grid-template-columns:minmax(0,1fr) auto!important;align-items:center!important;padding:4px!important}html.mz-native-app tbody tr:has(.status-not_cleaned) td{border:0!important;display:block!important;padding:11px 10px!important}html.mz-native-app tbody tr:has(.status-not_cleaned) td:nth-child(n+3){display:none!important}html.mz-native-app tbody tr:has(.status-not_cleaned) td::before{display:none!important}}}html.mz-native-android #advanced-link{display:flex!important;min-height:52px!important;align-items:center!important;justify-content:center!important;margin:8px 0 20px!important;padding:0 16px!important;border:1px solid rgba(255,255,255,.14)!important;border-radius:16px!important;background:rgba(255,255,255,.09)!important;color:#f4fbff!important;font-size:.9rem!important;font-weight:900!important;text-decoration:none!important}`;
  document.head.appendChild(style);
})();
